- hosts: localhost
  tasks:
    - name: "clear docker volumes"
      command: "sudo rm -rf ./volumes"
      args:
        chdir: ".."

    - name: "build docker images"
      command: "docker-compose build"
      args:
        chdir: ".."

    - name: "save docker images"
      command: "docker save -o {{ item }}.tar {{ item }}"
      args:
        chdir: ".."
      with_items: "{{ built_components }}"

    - name: "compress docker images"
      command: "gzip -f {{ item }}.tar"
      args:
        chdir: ".."
      with_items: "{{ built_components }}"

- hosts: all
  tasks:
    - name: create required directories
      file:
        path: "{{ item }}"
        state: directory
      with_items: "{{ app_dirs }}"

    - name: transfer required files to remote
      copy:
        src: "../{{ item }}"
        dest: "{{ app_dir }}/{{ item }}"
      with_items: "{{ copy_sources }}"

    - name: load docker images
      command: "docker load -i {{ app_dir }}/{{ item }}.tar.gz"
      with_items: "{{ built_components }}"

    - name: ensure containers are running
      command: "docker-compose -f docker-compose.remote.yaml up -d"
      args:
        chdir: "{{ app_dir }}"
