all:
  hosts:
    igrek.dev:
  vars:
    ansible_connection: ssh
    ansible_port: 2222
    ansible_user: root
    ask_pass: true
    ssh_args: "-o PubkeyAuthentication=yes -o PasswordAuthentication=yes -o ControlMaster=auto -o ControlPersist=60s"
    app_name: webdict
    app_dir: "/opt/{{ app_name }}"
    built_components:
      - webdict
    app_dirs:
      - "{{ app_dir }}"
      - "{{ app_dir }}/volumes/db"
    copy_sources:
      - "webdict.tar.gz"
      - "docker-compose.remote.yaml"
