version: '3'
services:

  webdict:
    build:
      context: ..
      dockerfile: deploy/docker/webdict/Dockerfile
    image: webdict
    container_name: webdict
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - "8081:8081"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Sh4QqTvAwR8TwzlW
      - MYSQL_PASSWORD=Sh4QqTvAwR8TwzlW
      - MYSQL_USER=webdict
      - MYSQL_DATABASE=webdict
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Sh4QqTvAwR8TwzlW
      - MYSQL_USER=webdict
      - MYSQL_PASSWORD=Sh4QqTvAwR8TwzlW
    links:
      - mysql:db
    ports:
      - "81:80"
    depends_on:
      - mysql
