INSERT INTO `user` (`id`, `login`, `pass`) VALUES
(2, 'jarek', 'dupa');

INSERT INTO `word` (`dictionary_id`, `user_id`, `name`, `definition`) VALUES
(1, 2, 'my bias', 'moje podejście, nastawienie, punkt widzenia'),
(1, 2, 'twofold', 'dwojaki'),
(1, 2, 'grasp', 'chwycić, zrozumieć'),
(1, 2, 'grab', 'chwycić, złapać'),
(1, 2, 'canvas', 'płótno np do malowania, pojęcie wykorzystywane w programowaniu w kontekście rysowania grafik'),
(1, 2, 'stilted', 'nienaturalny'),
(1, 2, 'invaluable', 'nieceniony'),
(1, 2, 'prevents', 'zapobiega'),
(1, 2, 'explicitly', 'wyraźnie'),
(1, 2, 'strive', 'starać się'),
(1, 2, 'scarce', 'deficytowy'),
(1, 2, 'exhausting', 'wyczerpujący'),
(1, 2, 'internally', 'wewnętrznie'),
(1, 2, 'obscured', 'zasłonięte'),
(1, 2, 'reminiscing', 'przywoływanie wspomnień'),
(1, 2, 'coverage', 'reportaż, omówienie prasowe, pokrycie'),
(1, 2, 'comprehensive', 'wszechstronny, obszerny'),
(1, 2, 'efforts', 'starania'),
(1, 2, 'press release', 'komunikat prasowy'),
(1, 2, 'fees', 'opłaty'),
(1, 2, 'redeem', 'wykupić, odkupić'),
(1, 2, 'audit', 'sprawdzenie, rewizja'),
(1, 2, 'sublime', 'wzniosły, idealny, wysublimowany'),
(1, 2, 'contribute', 'przyczynić się, wnieść wkład'),
(1, 2, 'utilize', 'wykorzystać, eksploatować'),
(1, 2, 'prompt', 'skłonić, namówić'),
(1, 2, 'assumption', 'założenie, hipoteza'),
(1, 2, 'attempt', 'próba, usiłowanie'),
(1, 2, 'appropriate', 'właściwy, stosowny'),
(1, 2, 'robust', 'silny, krzepki'),
(1, 2, 'home theater', 'kino domowe'),
(1, 2, 'puberty', 'dojrzewanie płciowe'),
(1, 2, 'omitting', 'pomijać'),
(1, 2, 'consecutive', 'kolejny, nieprzerwany, seryjny, następujący po czymś'),
(1, 2, 'auxiliary', 'Pomocniczy, posiłkowy'),
(1, 2, 'scheduled', 'planowy'),
(1, 2, 'suppress', 'stłumić, znieść'),
(1, 2, 'declined', 'odrzucony'),
(1, 2, 'quote', 'cytować'),
(1, 2, 'tender', 'delikatny'),
(1, 2, 'wreck', 'wrak'),
(1, 2, 'tribute', 'hołd, uznanie'),
(1, 2, 'explicit', 'wyraźny, kategoryczny'),
(1, 2, 'white paper', 'dokument reklamujący jakiś produkt ( ma jeszcze inne znaczenia )'),
(1, 2, 'resource efficiency', 'efektywność wykorzystania zasobów'),
(1, 2, 'sequality', 'sekwencja'),
(1, 2, 'executive', 'wykonawczy'),
(1, 2, 'esecutive summary', 'streszczenie');
