TRUNCATE `dict_entry`;
INSERT INTO `dict_entry` (`id`, `definition`, `dictionary_id`, `last_use`, `rank`, `word`) VALUES
(NULL, 'wspólnik, kojarzyć', '1', NULL, '0', 'associate'),
(NULL, 'oceniać', '1', NULL, '0', 'assess'),
(NULL, 'uzasadniony', '1', NULL, '0', 'legitimate'),
(NULL, 'umyślnie', '1', NULL, '0', 'admittedly'),
(NULL, 'współczesny', '1', NULL, '0', 'contemporary'),
(NULL, 'wszechobecny', '1', NULL, '0', 'ubiquitous'),
(NULL, 'zwięzłość', '1', NULL, '0', 'brevity'),
(NULL, 'zawierać', '1', NULL, '0', 'comprise'),
(NULL, 'pożerać', '1', NULL, '0', 'devour'),
(NULL, 'starać się', '1', NULL, '0', 'strive'),
(NULL, 'kompletny', '1', NULL, '0', 'utter'),
(NULL, 'opóźniać, odraczać', '1', NULL, '0', 'defer'),
(NULL, 'zostać poddanym', '1', NULL, '0', 'undergo'),
(NULL, 'nudny', '1', NULL, '0', 'tedious'),
(NULL, 'warstwa', '1', NULL, '0', 'tier'),
(NULL, 'z kolei', '1', NULL, '0', 'in turn'),
(NULL, 'nieodłączny', '1', NULL, '0', 'immanent'),
(NULL, 'zasługa', '1', NULL, '0', 'merit'),
(NULL, 'silny, surowy', '1', NULL, '0', 'severe'),
(NULL, 'gruntowny, dokładny', '1', NULL, '0', 'thorough'),
(NULL, 'w całym', '1', NULL, '0', 'throughout'),
(NULL, 'wybitny', '1', NULL, '0', 'eminent'),
(NULL, 'oddzielony', '1', NULL, '0', 'decoupled'),
(NULL, 'łączny', '1', NULL, '0', 'composite'),
(NULL, 'objazd', '1', NULL, '0', 'detour'),
(NULL, 'przyznawać się, wpuszczać', '1', NULL, '0', 'admit'),
(NULL, 'w związku z tym', '1', NULL, '0', 'accordingly'),
(NULL, 'przedstawiać', '1', NULL, '0', 'depict'),
(NULL, 'pojąć', '1', NULL, '0', 'conceive'),
(NULL, 'zawierać', '1', NULL, '0', 'comprise'),
(NULL, 'pamiętny', '1', NULL, '0', 'reminiscent'),
(NULL, 'powierzchowny', '1', NULL, '0', 'superficial'),
(NULL, 'solidny', '1', NULL, '0', 'robust'),
(NULL, 'opracować, dopracowany', '1', NULL, '0', 'elaborate'),
(NULL, 'skok', '1', NULL, '0', 'leap'),
(NULL, 'zawiły', '1', NULL, '0', 'intricate'),
(NULL, 'obmyślać', '1', NULL, '0', 'contrive'),
(NULL, 'pojęcie', '1', NULL, '0', 'notion'),
(NULL, 'zgodny', '1', NULL, '0', 'compliant'),
(NULL, 'zastraszać', '1', NULL, '0', 'intimidate'),
(NULL, 'wybitny, sławny', '1', NULL, '0', 'prominent'),
(NULL, 'wypukły', '1', NULL, '0', 'protuberant'),
(NULL, 'jeśli chodzi o, pod względem, z punktu widzenia', '1', NULL, '0', 'in terms of'),
(NULL, 'podatny', '1', NULL, '0', 'vulnerable'),
(NULL, 'wykorzystać', '1', NULL, '0', 'leverage'),
(NULL, 'nadający się', '1', NULL, '0', 'eligible'),
(NULL, 'celowy, przemyślany, rozważać', '1', NULL, '0', 'deliberate'),
(NULL, 'znaczny', '1', NULL, '0', 'substantial'),
(NULL, 'przegroda', '1', NULL, '0', 'compartment'),
(NULL, 'zwięzły', '1', NULL, '0', 'concise'),
(NULL, 'przysięga, przekleństwo', '1', NULL, '0', 'oath'),
(NULL, 'porzucony', '1', NULL, '0', 'derelict'),
(NULL, 'obdarzyć', '1', NULL, '0', 'endow'),
(NULL, 'trącić', '1', NULL, '0', 'nudge'),
(NULL, 'odwilż, rozmrażać', '1', NULL, '0', 'thaw'),
(NULL, 'rozwidlać się', '1', NULL, '0', 'bifurcate'),
(NULL, 'wysyłać', '1', NULL, '0', 'dispatch'),
(NULL, 'wierzchołek', '1', NULL, '0', 'summit'),
(NULL, 'zachować', '1', NULL, '0', 'retain'),
(NULL, 'skłonny', '1', NULL, '0', 'prone'),
(NULL, 'redukować, przycinać', '1', NULL, '0', 'prune'),
(NULL, 'domniemany', '1', NULL, '0', 'implicit'),
(NULL, 'wyraźny', '1', NULL, '0', 'explicit'),
(NULL, 'oddzielny, wyrazisty', '1', NULL, '0', 'distinct'),
(NULL, 'pęknięcie', '1', NULL, '0', 'rupture'),
(NULL, 'odwrotność, wzajemny, obustronny', '1', NULL, '0', 'reciprocal'),
(NULL, 'przestarzały', '1', NULL, '0', 'obsolete'),
(NULL, 'przymus', '1', NULL, '0', 'constraint'),
(NULL, 'zuchwałość', '1', NULL, '0', 'insolence'),
(NULL, 'zrozumieć', '1', NULL, '0', 'comprehend'),
(NULL, 'zrozumiały', '1', NULL, '0', 'comprehensible'),
(NULL, 'wszechstronny', '1', NULL, '0', 'comprehensive'),
(NULL, 'pomocniczy', '1', NULL, '0', 'auxiliary'),
(NULL, 'porzucic', '1', NULL, '0', 'forsake'),
(NULL, 'pochodzenie', '1', NULL, '0', 'ancestry'),
(NULL, 'odbiorca', '1', NULL, '0', 'recipient'),
(NULL, 'wzgląd', '1', NULL, '0', 'sake'),
(NULL, 'usiłować, dążenie', '1', NULL, '0', 'endeavour'),
(NULL, 'odzyskać', '1', NULL, '0', 'retrieve'),
(NULL, 'wycofać', '1', NULL, '0', 'retract'),
(NULL, 'powierzać, oddać', '1', NULL, '0', 'commit'),
(NULL, 'zobowiązanie', '1', NULL, '0', 'commitment'),
(NULL, 'sumaryczny', '1', NULL, '0', 'aggregate'),
(NULL, 'schować na potem', '1', NULL, '0', 'stash'),
(NULL, 'poprawić', '1', NULL, '0', 'amend'),
(NULL, 'zły, złośliwy', '1', NULL, '0', 'vicious'),
(NULL, 'wynurzać się (z mgły)', '1', NULL, '0', 'loom'),
(NULL, 'wykręcać', '1', NULL, '0', 'twine'),
(NULL, 'wiązka', '1', NULL, '0', 'bundle'),
(NULL, 'odwołać się, wezwać', '1', NULL, '0', 'invoke'),
(NULL, 'rusztowanie', '1', NULL, '0', 'scaffolding'),
(NULL, 'lokator', '1', NULL, '0', 'tenant'),
(NULL, 'wał', '1', NULL, '0', 'rampart'),
(NULL, 'przyzwoity', '1', NULL, '0', 'decent'),
(NULL, 'poprzedzać', '1', NULL, '0', 'precede'),
(NULL, 'wymazać', '1', NULL, '0', 'obliterate'),
(NULL, 'drugi', '1', NULL, '0', 'latter'),
(NULL, 'natknąć się, starcie', '1', NULL, '0', 'encounter'),
(NULL, 'nieład', '1', NULL, '0', 'clutter'),
(NULL, 'grupa', '1', NULL, '0', 'cluster'),
(NULL, 'zbędny', '1', NULL, '0', 'superfluous'),
(NULL, 'dyskretny', '1', NULL, '0', 'unobtrusive'),
(NULL, 'potomek', '1', NULL, '0', 'descendant'),
(NULL, 'mało prawdopodobne', '1', NULL, '0', 'unlikely'),
(NULL, 'odpychać', '1', NULL, '0', 'repel'),
(NULL, 'jęczmień', '1', NULL, '0', 'barley'),
(NULL, 'pszenica', '1', NULL, '0', 'wheat'),
(NULL, 'drożdże', '1', NULL, '0', 'yeast'),
(NULL, 'kukurydza', '1', NULL, '0', 'maize'),
(NULL, 'dojrzewać', '1', NULL, '0', 'ripen'),
(NULL, 'przeważać', '1', NULL, '0', 'outweigh'),
(NULL, 'obwód', '1', NULL, '0', 'perimeter'),
(NULL, 'podły', '1', NULL, '0', 'despicable'),
(NULL, 'streszczenie', '1', NULL, '0', 'synopsis'),
(NULL, 'współbieżny', '1', NULL, '0', 'concurrent'),
(NULL, 'zbieżny, zgodny, równoczesny', '1', NULL, '0', 'coincident'),
(NULL, 'wiarygodny', '1', NULL, '0', 'plausible'),
(NULL, 'paczka', '1', NULL, '0', 'parcel'),
(NULL, 'godność', '1', NULL, '0', 'dignity'),
(NULL, 'trwały', '1', NULL, '0', 'persistent'),
(NULL, 'wielokropek', '1', NULL, '0', 'ellipsis'),
(NULL, 'zamykać dostęp do', '1', NULL, '0', 'seal off'),
(NULL, 'wyłom, przełamać', '1', NULL, '0', 'breach'),
(NULL, 'nieprawdziwy', '1', NULL, '0', 'spurious'),
(NULL, 'dwuznaczny', '1', NULL, '0', 'ambiguous'),
(NULL, 'rzekomo', '1', NULL, '0', 'ostensibly'),
(NULL, 'stosowność', '1', NULL, '0', 'propriety'),
(NULL, 'własny', '1', NULL, '0', 'proprietary'),
(NULL, 'ograniczony', '1', NULL, '0', 'scarce'),
(NULL, 'przydział', '1', NULL, '0', 'quotas'),
(NULL, 'odchyłka, stronniczość, uprzedzenie', '1', NULL, '0', 'bias'),
(NULL, 'wpływ', '1', NULL, '0', 'leverage'),
(NULL, 'zaspokajać', '1', NULL, '0', 'cater'),
(NULL, 'niewygodny', '1', NULL, '0', 'cumbersome'),
(NULL, 'ładunek', '1', NULL, '0', 'payload'),
(NULL, 'wartownik', '1', NULL, '0', 'sentry'),
(NULL, 'wystarczać', '1', NULL, '0', 'suffice'),
(NULL, 'wyznaczać', '1', NULL, '0', 'designate'),
(NULL, 'oznaczyć', '1', NULL, '0', 'denote'),
(NULL, 'poziom', '1', NULL, '0', 'tier'),
(NULL, 'opracować, skomplikowany', '1', NULL, '0', 'elaborate'),
(NULL, 'późniejszy', '1', NULL, '0', 'subsequent'),
(NULL, 'granica', '1', NULL, '0', 'frontier'),
(NULL, 'opis', '1', NULL, '0', 'depiction'),
(NULL, 'faktura', '1', NULL, '0', 'invoice'),
(NULL, 'wnioskowanie', '1', NULL, '0', 'inference'),
(NULL, 'rozstrzygający', '1', NULL, '0', 'crucial'),
(NULL, 'stłumić', '1', NULL, '0', 'suppress'),
(NULL, 'podobieństwo', '1', NULL, '0', 'affinity'),
(NULL, 'rozszerzony', '1', NULL, '0', 'augmented'),
(NULL, 'mieszkaniec', '1', NULL, '0', 'inhabitant'),
(NULL, 'próbny', '1', NULL, '0', 'mock'),
(NULL, 'przechwytywać', '1', NULL, '0', 'intercept'),
(NULL, 'spadek, podupadać', '1', NULL, '0', 'decline'),
(NULL, 'poznawczy', '1', NULL, '0', 'cognitive'),
(NULL, 'przyległy', '1', NULL, '0', 'contiguous'),
(NULL, 'zestawić', '1', NULL, '0', 'collate'),
(NULL, 'dosłownie', '1', NULL, '0', 'verbatim'),
(NULL, 'wymuszenie', '1', NULL, '0', 'coercion'),
(NULL, 'całkowicie', '1', NULL, '0', 'thoroughly'),
(NULL, 'bez nadzoru', '1', NULL, '0', 'unattended'),
(NULL, 'pomimo to', '1', NULL, '0', 'nonetheless'),
(NULL, 'pierwszeństwo', '1', NULL, '0', 'precedence'),
(NULL, 'rodowód', '1', NULL, '0', 'pedigree'),
(NULL, 'wyłącznie', '1', NULL, '0', 'solely'),
(NULL, 'jedynie', '1', NULL, '0', 'merely'),
(NULL, 'dostosowywać się', '1', NULL, '0', 'conform'),
(NULL, 'sprzeczność', '1', NULL, '0', 'contradiction'),
(NULL, 'zmuszać', '1', NULL, '0', 'compel'),
(NULL, 'powstrzymywać', '1', NULL, '0', 'inhibit'),
(NULL, 'prawda', '1', NULL, '0', 'verity'),
(NULL, 'składać się', '1', NULL, '0', 'comprise'),
(NULL, 'cofać się', '1', NULL, '0', 'recede'),
(NULL, 'rozrzucać, rozproszyć się', '1', NULL, '0', 'scatter'),
(NULL, 'hurt', '1', NULL, '0', 'bulk'),
(NULL, 'unikać', '1', NULL, '0', 'evade'),
(NULL, 'oszacowanie', '1', NULL, '0', 'assessment'),
(NULL, 'zawierać', '1', NULL, '0', 'comprise'),
(NULL, 'pojmować', '1', NULL, '0', 'comprehend'),
(NULL, 'pełny', '1', NULL, '0', 'comprehensive'),
(NULL, 'przymus', '1', NULL, '0', 'coercion'),
(NULL, 'nagle', '1', NULL, '0', 'abruptly'),
(NULL, 'wytrwałość', '1', NULL, '0', 'perseverance'),
(NULL, 'zawiły, rozwijać', '1', NULL, '0', 'elaborate'),
(NULL, 'w związku z tym', '1', NULL, '0', 'hence');
